#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M
kotlin.native.ignoreDisabledTargets=true
kotlin.native.cacheKind=none
kotlin.experimental.swift-export.enabled=true
kotlin.mpp.enableCInteropCommonization=true
kotlin.mpp.enableCInteropCommonization.nowarn=true
kotlin.native.cacheKind.iosSimulatorArm64=none

#Gradle
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=false

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
#Moko
moko.resources.disableStaticFrameworkWarning=true